services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend
  migration:
    image: liquibase/liquibase:4.25
    container_name: liquibase
    depends_on:
      - db
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5437/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
volumes:
  postgresql: { }

networks:
  backend: { }
