github:
  base-url: https://api.github.com
stackoverflow:
  base-url: https://api.stackexchange.com/2.3
bot-local-host:
  base-url: http://localhost:8090

link:
  update:
    delay: 5000 # в миллисекундах

app:
  database-access-type: JPA
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
spring:
  application:
    name: scrapper
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5437/scrapper
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui
