global:
  evaluation_interval: 1m
  scrape_interval: 30s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['host.docker.internal:8091']
    metrics_path: /metrics
  - job_name: 'scrapper'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /metrics
